name: CI pipeline


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: ghcr.io/kanata27/delivery-pipeline:${{ github.sha }}

    
jobs:
  app-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore Delivery.sln
      
      - name: Build app
        run: dotnet build Delivery.sln -c Release --no-restore

      - name: Publish app
        run: dotnet publish ./src/Delivery.Api/Delivery.Api.csproj -c Release -o ./publish --no-build --no-restore 

      - name: Upload /publish as artifact
        uses: actions/upload-artifact@v7
        with: 
          name: publish
          path: ./publish
          retention-days: 30

      - name: Upload Dockerfile as artifact
        uses: actions/upload-artifact@v7
        with:
          name: Dockerfile
          path: ./Dockerfile
          retention-days: 30
          archive: false

  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs:
      - app-build
    steps: 

      - name: Download /publish artifact
        uses: actions/download-artifact@v8
        with:
          name: publish
          path: ./publish

      - name: Download Dockerfile artifact
        uses: actions/download-artifact@v8
        with:
          name: Dockerfile
          path: ./Dockerfile

      - name: Docker build image
        run: docker build -t "$DOCKER_IMAGE_NAME" -f ./Dockerfile/Dockerfile .

      - name: Docker change tag to latest
        run: docker tag "$DOCKER_IMAGE_NAME" ghcr.io/kanata27/delivery-pipeline:latest    

      - name: Run created image
        run: docker run -d --name csTestContainer -p 8080:8080 "$DOCKER_IMAGE_NAME"

      - name: Healthcheck container
        run: |
          for (( i=1; i<=5; i++ ))
          do
            if ! curl -f http://localhost:8080/health; then
              sleep 3s
            else 
              exit 0
            fi
          done
          exit 1

      - name: Stop container
        if: always()
        run: docker rm -f csTestContainer

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   

      - name: Push an image to GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push "$DOCKER_IMAGE_NAME"
          docker push ghcr.io/kanata27/delivery-pipeline:latest

  verify-registry:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - docker
    permissions:
      packages: read
    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image from GHCR
        run: docker pull "$DOCKER_IMAGE_NAME"

      - name: Run created image
        run: docker run -d --name csTestContainer -p 8080:8080 "$DOCKER_IMAGE_NAME"

      - name: Healthcheck container
        run: |
          for (( i=1; i<=5; i++ ))
          do
            if ! curl -f http://localhost:8080/health; then
              sleep 3s
            else
              exit 0
            fi
          done
          exit 1

      - name: Stop container
        if: always()
        run: docker rm -f csTestContainer
