name: CI pipeline


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  app-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore Delivery.sln
      
      - name: Build app
        run: dotnet build Delivery.sln -c Release --no-restore

      - name: Publish app
        run: dotnet publish ./src/Delivery.Api/Delivery.Api.csproj -c Release -o ./publish --no-build --no-restore 

      - name: Upload /publish as artifact
        uses: actions/upload-artifact@v7
        with: 
          name: publish
          path: ./publish
          retention-days: 30

      - name: Upload Dockerfile as artifact
        uses: actions/upload-artifact@v7
        with:
          name: Dockerfile
          path: ./Dockerfile
          retention-days: 30
          archive: false

  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    env:
      DOCKER_IMAGE_NAME: cs_app_${{ github.sha }}
    needs:
      - app-build
    steps: 

      - name: Download /publish artifact
        uses: actions/download-artifact@v8
        with:
          name: publish
          path: ./publish

      - name: Download Dockerfile artifact
        uses: actions/download-artifact@v8
        with:
          name: Dockerfile
          path: ./Dockerfile

      - name: Check files and directories
        run: ls -la

      - name: Docker build image
        run: docker build -t "$DOCKER_IMAGE_NAME" ./Dockerfile

      - name: Check docker images
        run: docker images
